# Generated by Django 5.1.1 on 2024-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('tecnologia', models.CharField(max_length=50)),
                ('descrip', models.CharField(max_length=1000)),
                ('color', models.CharField(max_length=50)),
                ('fotos', models.ImageField(null=True, upload_to='producto')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
