# Generated by Django 5.1.1 on 2024-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
