# Generated by Django 5.1.1 on 2024-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek', '0006_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotos',
            field=models.ImageField(null=True, upload_to='producto/'),
        ),
    ]
